name: NyaBackup
version: '1.1.2'
main: me.norax.nyaBackup.NyaBackup
api-version: '1.21'

commands:
  nyabackup:
    description: main nyabackup manager.
    usage: /nyabackup <new/list/load/info>
    permission: nyabackup.manager

